---
title: Ken Booth
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: 'Ken Booth'
    feature_image: https://kenbooth.net/assets/images/DSC00758-1.jpg
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
theme: alembic-jekyll-theme
# master: https://github.com/daviddarnes/alembic
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
url: https://kenbooth.net
baseurl: ''
description: Ken Booth's home page on the internet and library of miscellany.
permalink: "/:title:output_ext"
logo: https://kenbooth.net/assets/images/kb.png
paginate: 5
paginate_path: "/page:num"
navigation_header:
- title: Home
  url: "/"
- title: About
  url: "/about/"
- title: RSS
  url: "/feed.xml"
navigation_footer:
- title: Back to top
  url: "#top"
fonts:
  preconnect_urls:
  - https://fonts.gstatic.com
  font_urls:
  - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
  - https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap
