# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://kenbooth.net'
baseurl: ''
title: 'Ken Booth'
description: "Ken Booth's home page on the internet and library of miscellany."
permalink: /:title:output_ext
logo: "https://kenbooth.net/assets/images/kb.png"

# Pagination
paginate: 5
paginate_path: /page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: RSS
  url: /feed.xml

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Ken Booth
    feature_image: "https://kenbooth.net/assets/images/DSC00758-1.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
    - https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap
